sudo: false

language: ruby

cache: bundler

services: mongodb

rvm:
  - 2.6.6
  - 2.7.2

env:
  - MONGOID_VERSION=HEAD
  - MONGOID_VERSION=7

before_install:
  - gem update bundler

before_script:
  - echo "replication:\n  replSetName: \"rs0\"" | sudo tee -a /etc/mongod.conf
  - sudo service mongod restart
  - mongo --eval 'rs.initiate({_id: "rs0", members: [{"_id":1, "host":"localhost:27017"}]})'
  - mongo --eval 'rs.status()'

matrix:
  fast_finish: true
  allow_failures:
    - env: MONGOID_VERSION=HEAD
