sudo: false

language: ruby

cache: bundler

services: mongodb

rvm:
  - 2.6.6
  - 2.7.2

env:
  - MONGOID_VERSION=HEAD
  - MONGOID_VERSION=7

before_install:
  - gem update bundler

before_script:
  - sleep 15
  - |
    mongo admin --eval 'db.createUser({ user: "root", pwd: "12345", roles: [{ role: "root", db: "admin" }] })'
  - 'echo "replication:" | sudo tee -a /etc/mongod.conf'
  - 'echo "  replSetName: rs0" | sudo tee -a /etc/mongod.conf'
  - sudo systemctl restart mongod
  - sleep 20
  - mongo -u root -p 12345 --eval 'rs.initiate()'
  # - |
  #   mongo -u root -p 12345 --eval 'rs.initiate({_id: "rs0", members: [{_id: 1, host: "localhost:27017"}]})'

matrix:
  fast_finish: true
  allow_failures:
    - env: MONGOID_VERSION=HEAD
